from __future__ import annotations

import hashlib
import json
import os
import zipfile
from pathlib import Path
from typing import Any, cast

from mythweaver.builders.paths import safe_file_name, safe_relative_path, safe_slug
from mythweaver.catalog.loaders import modrinth_loader_category
from mythweaver.schemas.contracts import BuildArtifact, CandidateMod, ResolvedPack


def _content_kind(mod: CandidateMod) -> str:
    return getattr(mod, "content_kind", "mod") or "mod"


def _placement(mod: CandidateMod) -> str | None:
    p = getattr(mod, "content_placement", None)
    return str(p) if p is not None else None


def _loader_dependency_key(loader: str) -> str:
    normalized = modrinth_loader_category(loader)
    if not normalized:
        raise ValueError(f"unsupported Modrinth loader dependency: {loader}")
    if normalized == "fabric":
        return "fabric-loader"
    if normalized == "quilt":
        return "quilt-loader"
    return normalized


def _file_entry(mod: CandidateMod) -> dict[str, object]:
    kind = _content_kind(mod)
    file = mod.primary_file()
    filename = safe_file_name(file.filename)
    if kind == "mod":
        path = f"mods/{filename}"
    elif kind == "resourcepack":
        path = f"overrides/resourcepacks/{filename}"
    elif kind == "shaderpack":
        path = f"overrides/shaderpacks/{filename}"
    else:
        raise ValueError(f"unsupported mrpack file kind: {kind}")
    sha1 = file.hashes.get("sha1")
    sha512 = file.hashes.get("sha512")
    if not sha1 or not sha512:
        raise ValueError(f"mrpack export requires sha1 and sha512 hashes for {filename!r}")
    return {
        "path": path,
        "hashes": {
            "sha1": sha1,
            "sha512": sha512,
        },
        "downloads": [file.url],
        "fileSize": file.size,
    }


def _version_id(pack: ResolvedPack) -> str:
    payload = {
        "name": pack.name,
        "minecraft_version": pack.minecraft_version,
        "loader": pack.loader,
        "loader_version": pack.loader_version,
        "mods": [
            {
                "project_id": mod.project_id,
                "version_id": mod.selected_version.id,
                "file": mod.primary_file().filename,
                "sha512": mod.primary_file().hashes["sha512"],
                "content_kind": _content_kind(mod),
            }
            for mod in pack.selected_mods
        ],
    }
    digest = hashlib.sha1(json.dumps(payload, sort_keys=True).encode("utf-8")).hexdigest()[:12]
    return f"{safe_slug(pack.name, fallback='mythweaver-pack')}-{digest}"


def build_mrpack(
    pack: ResolvedPack,
    output_path: Path,
    overrides: dict[str, Path] | None = None,
    summary: str | None = None,
) -> BuildArtifact:
    """Write an official Modrinth .mrpack archive."""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    dependencies: dict[str, str] = {"minecraft": pack.minecraft_version}
    if pack.loader_version:
        dependencies[_loader_dependency_key(pack.loader)] = pack.loader_version

    files_out: list[dict[str, object]] = []
    valid_env_values = {"required", "optional", "unsupported"}
    for mod in pack.selected_mods:
        kind = _content_kind(mod)
        if kind == "datapack" and _placement(mod) == "manual_world_creation":
            continue
        fe = _file_entry(mod)
        if kind == "shaderpack":
            fe["env"] = {"client": "required", "server": "unsupported"}
        elif kind == "resourcepack":
            if mod.client_side in valid_env_values and mod.server_side in valid_env_values:
                fe["env"] = {"client": mod.client_side, "server": mod.server_side}
            else:
                fe["env"] = {"client": "required", "server": "optional"}
        elif kind == "mod" and mod.client_side in valid_env_values and mod.server_side in valid_env_values:
            fe["env"] = {"client": mod.client_side, "server": mod.server_side}
        files_out.append(fe)

    index = {
        "formatVersion": 1,
        "game": "minecraft",
        "versionId": _version_id(pack),
        "name": pack.name,
        "summary": summary or f"Generated by MythWeaver for {pack.name}.",
        "files": files_out,
        "dependencies": dependencies,
    }

    with zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr(
            "modrinth.index.json",
            json.dumps(index, indent=2, sort_keys=True).encode("utf-8"),
        )
        for target, source in (overrides or {}).items():
            safe_target = safe_relative_path(target)
            source_path = Path(source)
            if not source_path.is_file():
                raise FileNotFoundError(source_path)
            archive.write(source_path, f"overrides/{safe_target.as_posix()}")

    validate_mrpack_archive(output_path)
    return BuildArtifact(
        kind="mrpack",
        path=os.fspath(output_path),
        metadata={"selected_mods": len(pack.selected_mods)},
    )


def validate_mrpack_archive(path: Path) -> dict[str, Any]:
    """Verify the archive shape MythWeaver just wrote before reporting an artifact."""

    if not Path(path).is_file():
        raise FileNotFoundError(path)
    with zipfile.ZipFile(path) as archive:
        names = set(archive.namelist())
        if "modrinth.index.json" not in names:
            raise ValueError("mrpack archive is missing modrinth.index.json")
        index = json.loads(archive.read("modrinth.index.json"))
    required_top_level = {"formatVersion", "game", "versionId", "name", "files", "dependencies"}
    missing = required_top_level - set(index)
    if missing:
        raise ValueError(f"mrpack index missing required fields: {', '.join(sorted(missing))}")
    if index["formatVersion"] != 1 or index["game"] != "minecraft":
        raise ValueError("mrpack index has unsupported formatVersion or game")
    return cast(dict[str, Any], index)
