from __future__ import annotations

import hashlib
import json
import os
import zipfile
from pathlib import Path
from typing import Any

from mythweaver.builders.paths import safe_file_name, safe_relative_path, safe_slug
from mythweaver.schemas.contracts import BuildArtifact, CandidateMod, ResolvedPack


def _loader_dependency_key(loader: str) -> str:
    if loader == "fabric":
        return "fabric-loader"
    if loader == "quilt":
        return "quilt-loader"
    return loader


def _file_entry(mod: CandidateMod) -> dict[str, object]:
    file = mod.primary_file()
    filename = safe_file_name(file.filename)
    entry: dict[str, object] = {
        "path": f"mods/{filename}",
        "hashes": {
            "sha1": file.hashes["sha1"],
            "sha512": file.hashes["sha512"],
        },
        "downloads": [file.url],
        "fileSize": file.size,
    }
    valid_env_values = {"required", "optional", "unsupported"}
    if mod.client_side in valid_env_values and mod.server_side in valid_env_values:
        entry["env"] = {
            "client": mod.client_side,
            "server": mod.server_side,
        }
    return entry


def _version_id(pack: ResolvedPack) -> str:
    payload = {
        "name": pack.name,
        "minecraft_version": pack.minecraft_version,
        "loader": pack.loader,
        "loader_version": pack.loader_version,
        "mods": [
            {
                "project_id": mod.project_id,
                "version_id": mod.selected_version.id,
                "file": mod.primary_file().filename,
                "sha512": mod.primary_file().hashes["sha512"],
            }
            for mod in pack.selected_mods
        ],
    }
    digest = hashlib.sha1(json.dumps(payload, sort_keys=True).encode("utf-8")).hexdigest()[:12]
    return f"{safe_slug(pack.name, fallback='mythweaver-pack')}-{digest}"


def build_mrpack(
    pack: ResolvedPack,
    output_path: Path,
    overrides: dict[str, Path] | None = None,
    summary: str | None = None,
) -> BuildArtifact:
    """Write an official Modrinth .mrpack archive."""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    dependencies: dict[str, str] = {"minecraft": pack.minecraft_version}
    if pack.loader_version:
        dependencies[_loader_dependency_key(pack.loader)] = pack.loader_version

    index = {
        "formatVersion": 1,
        "game": "minecraft",
        "versionId": _version_id(pack),
        "name": pack.name,
        "summary": summary or f"Generated by MythWeaver for {pack.name}.",
        "files": [_file_entry(mod) for mod in pack.selected_mods],
        "dependencies": dependencies,
    }

    with zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr(
            "modrinth.index.json",
            json.dumps(index, indent=2, sort_keys=True).encode("utf-8"),
        )
        for target, source in (overrides or {}).items():
            safe_target = safe_relative_path(target)
            source_path = Path(source)
            if not source_path.is_file():
                raise FileNotFoundError(source_path)
            archive.write(source_path, f"overrides/{safe_target.as_posix()}")

    validate_mrpack_archive(output_path)
    return BuildArtifact(
        kind="mrpack",
        path=os.fspath(output_path),
        metadata={"selected_mods": len(pack.selected_mods)},
    )


def validate_mrpack_archive(path: Path) -> dict[str, Any]:
    """Verify the archive shape MythWeaver just wrote before reporting an artifact."""

    if not Path(path).is_file():
        raise FileNotFoundError(path)
    with zipfile.ZipFile(path) as archive:
        names = set(archive.namelist())
        if "modrinth.index.json" not in names:
            raise ValueError("mrpack archive is missing modrinth.index.json")
        index = json.loads(archive.read("modrinth.index.json"))
    required_top_level = {"formatVersion", "game", "versionId", "name", "files", "dependencies"}
    missing = required_top_level - set(index)
    if missing:
        raise ValueError(f"mrpack index missing required fields: {', '.join(sorted(missing))}")
    if index["formatVersion"] != 1 or index["game"] != "minecraft":
        raise ValueError("mrpack index has unsupported formatVersion or game")
    return index
