from __future__ import annotations

import configparser
import json
import shutil
from pathlib import Path

from mythweaver.builders.paths import safe_file_name, safe_slug
from mythweaver.schemas.contracts import BuildArtifact, ResolvedPack


def _instance_id(name: str) -> str:
    return safe_slug(name, fallback="mythweaver-pack")


def _component_uid(loader: str) -> str:
    if loader == "fabric":
        return "net.fabricmc.fabric-loader"
    if loader == "quilt":
        return "org.quiltmc.quilt-loader"
    if loader == "neoforge":
        return "net.neoforged"
    return "net.minecraftforge"


def _write_instance_cfg(path: Path, pack: ResolvedPack, memory_mb: int | None = None) -> None:
    config = configparser.ConfigParser()
    config.optionxform = str
    config["General"] = {
        "ConfigVersion": "1.2",
        "InstanceType": "OneSix",
        "name": pack.name,
        "notes": "Generated by MythWeaver.",
    }
    if memory_mb is not None:
        config["General"]["MaxMemAlloc"] = str(memory_mb)
    with path.open("w", encoding="utf-8") as handle:
        config.write(handle, space_around_delimiters=False)


def _write_mmc_pack(path: Path, pack: ResolvedPack) -> None:
    components = [
        {
            "uid": "net.minecraft",
            "version": pack.minecraft_version,
        }
    ]
    if pack.loader_version:
        components.append(
            {
                "uid": _component_uid(pack.loader),
                "version": pack.loader_version,
            }
        )
    path.write_text(
        json.dumps({"formatVersion": 1, "components": components}, indent=2),
        encoding="utf-8",
    )


def build_prism_instance(
    pack: ResolvedPack,
    instances_root: Path,
    *,
    downloaded_files: dict[str, Path],
    memory_mb: int | None = None,
) -> BuildArtifact:
    """Create a Prism/MultiMC-compatible local instance folder."""

    instance_dir = Path(instances_root) / _instance_id(pack.name)
    minecraft_dir = instance_dir / ".minecraft"
    mods_dir = minecraft_dir / "mods"
    mods_dir.mkdir(parents=True, exist_ok=True)

    _write_instance_cfg(instance_dir / "instance.cfg", pack, memory_mb)
    _write_mmc_pack(instance_dir / "mmc-pack.json", pack)

    for mod in pack.selected_mods:
        source = downloaded_files.get(mod.project_id)
        if source is None:
            raise FileNotFoundError(f"missing downloaded file for {mod.project_id}")
        destination = mods_dir / safe_file_name(mod.primary_file().filename)
        shutil.copy2(source, destination)

    return BuildArtifact(
        kind="prism-instance",
        path=str(instance_dir),
        metadata={"instance_id": instance_dir.name, "selected_mods": len(pack.selected_mods)},
    )
