from __future__ import annotations

import configparser
import hashlib
import json
import os
import shutil
import urllib.request
from pathlib import Path

from mythweaver.builders.paths import safe_file_name, safe_slug
from mythweaver.catalog.loaders import prism_component_uid
from mythweaver.schemas.contracts import BuildArtifact, SourceFileCandidate, SourceResolveReport


def build_source_instance(
    report: SourceResolveReport,
    output_root: Path,
    *,
    name: str,
    loader_version: str | None = None,
    user_agent: str = "MythWeaver",
    prism: bool = True,
) -> BuildArtifact:
    instance_dir = Path(output_root) / safe_slug(name, fallback="mythweaver-pack")
    minecraft_dir = instance_dir / ".minecraft"
    mods_dir = minecraft_dir / "mods"
    mods_dir.mkdir(parents=True, exist_ok=True)

    _write_instance_cfg(instance_dir / "instance.cfg", name)
    _write_mmc_pack(instance_dir / "mmc-pack.json", report, loader_version=loader_version)
    for candidate in report.selected_files:
        source = _acquire_source_file(candidate, instance_dir / "cache", user_agent)
        file_name = candidate.file_name or Path(source).name
        shutil.copy2(source, mods_dir / safe_file_name(file_name))

    return BuildArtifact(
        kind="prism-instance" if prism else "local-instance",
        path=os.fspath(instance_dir),
        metadata={"selected_files": len(report.selected_files)},
    )


def _write_instance_cfg(path: Path, name: str) -> None:
    config = configparser.ConfigParser()
    config["General"] = {
        "ConfigVersion": "1.2",
        "InstanceType": "OneSix",
        "name": name,
        "notes": "Generated by MythWeaver from verified source candidates.",
    }
    with path.open("w", encoding="utf-8") as handle:
        config.write(handle, space_around_delimiters=False)


def _write_mmc_pack(path: Path, report: SourceResolveReport, *, loader_version: str | None) -> None:
    components = [{"uid": "net.minecraft", "version": report.minecraft_version}]
    uid = prism_component_uid(report.loader)
    if loader_version and not uid:
        raise ValueError(f"unsupported Prism loader component: {report.loader}")
    if uid and loader_version:
        components.append({"uid": uid, "version": loader_version})
    path.write_text(json.dumps({"formatVersion": 1, "components": components}, indent=2), encoding="utf-8")


def _acquire_source_file(candidate: SourceFileCandidate, cache_root: Path, user_agent: str) -> Path:
    if not candidate.download_url:
        raise ValueError(f"{candidate.name} has no download URL or local path.")
    source = Path(candidate.download_url)
    if candidate.source == "local" or source.is_file():
        if not _verify_hashes(source, candidate.hashes):
            raise ValueError(f"local file failed hash verification: {source}")
        return source
    if not candidate.download_url.startswith("https://"):
        raise ValueError(f"refusing non-HTTPS source download: {candidate.download_url}")
    destination = cache_root / safe_file_name(candidate.project_id or candidate.slug or candidate.name) / safe_file_name(
        candidate.file_name or f"{candidate.name}.jar"
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    request = urllib.request.Request(candidate.download_url, headers={"User-Agent": user_agent})
    with urllib.request.urlopen(request, timeout=60) as response:
        tmp_path = destination.with_suffix(destination.suffix + ".part")
        with tmp_path.open("wb") as handle:
            while True:
                chunk = response.read(1024 * 1024)
                if not chunk:
                    break
                handle.write(chunk)
        os.replace(tmp_path, destination)
    if not _verify_hashes(destination, candidate.hashes):
        raise ValueError(f"downloaded file failed hash verification: {destination}")
    return destination


def _verify_hashes(path: Path, hashes: dict[str, str]) -> bool:
    if not hashes or not path.is_file():
        return False
    checked = False
    for algorithm, expected in hashes.items():
        if algorithm not in {"sha1", "sha512", "md5"}:
            continue
        checked = True
        digest = hashlib.new(algorithm)
        with path.open("rb") as handle:
            for chunk in iter(lambda: handle.read(1024 * 1024), b""):
                digest.update(chunk)
        if digest.hexdigest().lower() != expected.lower():
            return False
    return checked
